import { Link } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="./product/bots">
        <a>Go to bots page</a>
      </Link><br/>
      <Link href="./product/messenger">
        <a>Go to messenger page</a>
      </Link>
    </div>
  )
}
